// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/taxease-redesign/Cockpit.tsx": () => import("../components/mockups/taxease-redesign/Cockpit.tsx"),
  "./components/mockups/taxease-redesign/Editorial.tsx": () => import("../components/mockups/taxease-redesign/Editorial.tsx"),
  "./components/mockups/taxease-redesign/Glass.tsx": () => import("../components/mockups/taxease-redesign/Glass.tsx"),
  "./components/mockups/taxease-v4/Conversational.tsx": () => import("../components/mockups/taxease-v4/Conversational.tsx"),
  "./components/mockups/taxease-v4/FlowMap.tsx": () => import("../components/mockups/taxease-v4/FlowMap.tsx"),
  "./components/mockups/taxease-v4/Scorecard.tsx": () => import("../components/mockups/taxease-v4/Scorecard.tsx"),
  "./components/mockups/taxease-v4/Timeline.tsx": () => import("../components/mockups/taxease-v4/Timeline.tsx")
};
