// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/taxease-redesign/Cockpit.tsx": () => import("../components/mockups/taxease-redesign/Cockpit.tsx"),
  "./components/mockups/taxease-redesign/Editorial.tsx": () => import("../components/mockups/taxease-redesign/Editorial.tsx"),
  "./components/mockups/taxease-redesign/Glass.tsx": () => import("../components/mockups/taxease-redesign/Glass.tsx")
};
